# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GRA8HI\Documents\Projects\Test_Environment_Client\qt_designer\SwitchBoxWidget.ui'
#
# Created: Tue Feb 14 16:28:17 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_switchBoxWidget(object):
    def setupUi(self, switchBoxWidget):
        switchBoxWidget.setObjectName("switchBoxWidget")
        self.verticalLayout = QtGui.QVBoxLayout(switchBoxWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.typeFrame = QtGui.QFrame(switchBoxWidget)
        self.typeFrame.setObjectName("typeFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.typeFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typeLabel = QtGui.QLabel(self.typeFrame)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout.addWidget(self.typeLabel)
        self.typeComboBox = QtGui.QComboBox(self.typeFrame)
        self.typeComboBox.setObjectName("typeComboBox")
        self.horizontalLayout.addWidget(self.typeComboBox)
        self.portLineEdit = QtGui.QLineEdit(self.typeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portLineEdit.sizePolicy().hasHeightForWidth())
        self.portLineEdit.setSizePolicy(sizePolicy)
        self.portLineEdit.setObjectName("portLineEdit")
        self.horizontalLayout.addWidget(self.portLineEdit)
        self.verticalLayout.addWidget(self.typeFrame)
        self.optionsHorizontalLayout = QtGui.QHBoxLayout()
        self.optionsHorizontalLayout.setObjectName("optionsHorizontalLayout")
        self.portsGroupBox = QtGui.QGroupBox(switchBoxWidget)
        self.portsGroupBox.setObjectName("portsGroupBox")
        self.portsFormLayout = QtGui.QFormLayout(self.portsGroupBox)
        self.portsFormLayout.setObjectName("portsFormLayout")
        self.port1Label = QtGui.QLabel(self.portsGroupBox)
        self.port1Label.setObjectName("port1Label")
        self.portsFormLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.port1Label)
        self.port1LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port1LineEdit.setObjectName("port1LineEdit")
        self.portsFormLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.port1LineEdit)
        self.port2Label = QtGui.QLabel(self.portsGroupBox)
        self.port2Label.setObjectName("port2Label")
        self.portsFormLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.port2Label)
        self.port2LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port2LineEdit.setObjectName("port2LineEdit")
        self.portsFormLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.port2LineEdit)
        self.port3Label = QtGui.QLabel(self.portsGroupBox)
        self.port3Label.setObjectName("port3Label")
        self.portsFormLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.port3Label)
        self.port3LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port3LineEdit.setObjectName("port3LineEdit")
        self.portsFormLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.port3LineEdit)
        self.port4Label = QtGui.QLabel(self.portsGroupBox)
        self.port4Label.setObjectName("port4Label")
        self.portsFormLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.port4Label)
        self.port4LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port4LineEdit.setObjectName("port4LineEdit")
        self.portsFormLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.port4LineEdit)
        self.port5Label = QtGui.QLabel(self.portsGroupBox)
        self.port5Label.setObjectName("port5Label")
        self.portsFormLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.port5Label)
        self.port5LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port5LineEdit.setObjectName("port5LineEdit")
        self.portsFormLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.port5LineEdit)
        self.port6Label = QtGui.QLabel(self.portsGroupBox)
        self.port6Label.setObjectName("port6Label")
        self.portsFormLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.port6Label)
        self.port6LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port6LineEdit.setObjectName("port6LineEdit")
        self.portsFormLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.port6LineEdit)
        self.port7Label = QtGui.QLabel(self.portsGroupBox)
        self.port7Label.setObjectName("port7Label")
        self.portsFormLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.port7Label)
        self.port7LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port7LineEdit.setObjectName("port7LineEdit")
        self.portsFormLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.port7LineEdit)
        self.port8Label = QtGui.QLabel(self.portsGroupBox)
        self.port8Label.setObjectName("port8Label")
        self.portsFormLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.port8Label)
        self.port8LineEdit = QtGui.QLineEdit(self.portsGroupBox)
        self.port8LineEdit.setObjectName("port8LineEdit")
        self.portsFormLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.port8LineEdit)
        self.optionsHorizontalLayout.addWidget(self.portsGroupBox)
        self.aliasesGroupBox = QtGui.QGroupBox(switchBoxWidget)
        self.aliasesGroupBox.setObjectName("aliasesGroupBox")
        self.gridLayout = QtGui.QGridLayout(self.aliasesGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.alias8Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias8Label.setObjectName("alias8Label")
        self.gridLayout.addWidget(self.alias8Label, 7, 0, 1, 1)
        self.alias8LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias8LineEdit.setObjectName("alias8LineEdit")
        self.gridLayout.addWidget(self.alias8LineEdit, 7, 1, 1, 1)
        self.alias1ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias1ComboBox.setObjectName("alias1ComboBox")
        self.gridLayout.addWidget(self.alias1ComboBox, 0, 3, 1, 1)
        self.alias7Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias7Label.setObjectName("alias7Label")
        self.gridLayout.addWidget(self.alias7Label, 6, 0, 1, 1)
        self.alias6LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias6LineEdit.setObjectName("alias6LineEdit")
        self.gridLayout.addWidget(self.alias6LineEdit, 5, 1, 1, 1)
        self.alias7LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias7LineEdit.setObjectName("alias7LineEdit")
        self.gridLayout.addWidget(self.alias7LineEdit, 6, 1, 1, 1)
        self.alias6Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias6Label.setObjectName("alias6Label")
        self.gridLayout.addWidget(self.alias6Label, 5, 0, 1, 1)
        self.alias4LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias4LineEdit.setObjectName("alias4LineEdit")
        self.gridLayout.addWidget(self.alias4LineEdit, 3, 1, 1, 1)
        self.alias3LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias3LineEdit.setObjectName("alias3LineEdit")
        self.gridLayout.addWidget(self.alias3LineEdit, 2, 1, 1, 1)
        self.alias1Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias1Label.setObjectName("alias1Label")
        self.gridLayout.addWidget(self.alias1Label, 0, 0, 1, 1)
        self.alias1LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias1LineEdit.setObjectName("alias1LineEdit")
        self.gridLayout.addWidget(self.alias1LineEdit, 0, 1, 1, 1)
        self.alias2LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias2LineEdit.setObjectName("alias2LineEdit")
        self.gridLayout.addWidget(self.alias2LineEdit, 1, 1, 1, 1)
        self.alias3Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias3Label.setObjectName("alias3Label")
        self.gridLayout.addWidget(self.alias3Label, 2, 0, 1, 1)
        self.alias2Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias2Label.setObjectName("alias2Label")
        self.gridLayout.addWidget(self.alias2Label, 1, 0, 1, 1)
        self.alias4Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias4Label.setObjectName("alias4Label")
        self.gridLayout.addWidget(self.alias4Label, 3, 0, 1, 1)
        self.alias5Label = QtGui.QLabel(self.aliasesGroupBox)
        self.alias5Label.setObjectName("alias5Label")
        self.gridLayout.addWidget(self.alias5Label, 4, 0, 1, 1)
        self.alias5LineEdit = QtGui.QLineEdit(self.aliasesGroupBox)
        self.alias5LineEdit.setObjectName("alias5LineEdit")
        self.gridLayout.addWidget(self.alias5LineEdit, 4, 1, 1, 1)
        self.for1Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for1Label.setObjectName("for1Label")
        self.gridLayout.addWidget(self.for1Label, 0, 2, 1, 1)
        self.alias2ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias2ComboBox.setObjectName("alias2ComboBox")
        self.gridLayout.addWidget(self.alias2ComboBox, 1, 3, 1, 1)
        self.alias3ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias3ComboBox.setObjectName("alias3ComboBox")
        self.gridLayout.addWidget(self.alias3ComboBox, 2, 3, 1, 1)
        self.alias4ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias4ComboBox.setObjectName("alias4ComboBox")
        self.gridLayout.addWidget(self.alias4ComboBox, 3, 3, 1, 1)
        self.alias5ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias5ComboBox.setObjectName("alias5ComboBox")
        self.gridLayout.addWidget(self.alias5ComboBox, 4, 3, 1, 1)
        self.alias6ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias6ComboBox.setObjectName("alias6ComboBox")
        self.gridLayout.addWidget(self.alias6ComboBox, 5, 3, 1, 1)
        self.alias7ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias7ComboBox.setObjectName("alias7ComboBox")
        self.gridLayout.addWidget(self.alias7ComboBox, 6, 3, 1, 1)
        self.alias8ComboBox = QtGui.QComboBox(self.aliasesGroupBox)
        self.alias8ComboBox.setObjectName("alias8ComboBox")
        self.gridLayout.addWidget(self.alias8ComboBox, 7, 3, 1, 1)
        self.for2Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for2Label.setObjectName("for2Label")
        self.gridLayout.addWidget(self.for2Label, 1, 2, 1, 1)
        self.for3Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for3Label.setObjectName("for3Label")
        self.gridLayout.addWidget(self.for3Label, 2, 2, 1, 1)
        self.for4Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for4Label.setObjectName("for4Label")
        self.gridLayout.addWidget(self.for4Label, 3, 2, 1, 1)
        self.for5Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for5Label.setObjectName("for5Label")
        self.gridLayout.addWidget(self.for5Label, 4, 2, 1, 1)
        self.for6Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for6Label.setObjectName("for6Label")
        self.gridLayout.addWidget(self.for6Label, 5, 2, 1, 1)
        self.for7Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for7Label.setObjectName("for7Label")
        self.gridLayout.addWidget(self.for7Label, 6, 2, 1, 1)
        self.for8Label = QtGui.QLabel(self.aliasesGroupBox)
        self.for8Label.setObjectName("for8Label")
        self.gridLayout.addWidget(self.for8Label, 7, 2, 1, 1)
        self.optionsHorizontalLayout.addWidget(self.aliasesGroupBox)
        self.verticalLayout.addLayout(self.optionsHorizontalLayout)

        self.retranslateUi(switchBoxWidget)
        QtCore.QMetaObject.connectSlotsByName(switchBoxWidget)

    def retranslateUi(self, switchBoxWidget):
        switchBoxWidget.setWindowTitle(QtGui.QApplication.translate("switchBoxWidget", "Switch Box", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("switchBoxWidget", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.portsGroupBox.setTitle(QtGui.QApplication.translate("switchBoxWidget", "Ports", None, QtGui.QApplication.UnicodeUTF8))
        self.port1Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port1", None, QtGui.QApplication.UnicodeUTF8))
        self.port2Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port2", None, QtGui.QApplication.UnicodeUTF8))
        self.port3Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port3", None, QtGui.QApplication.UnicodeUTF8))
        self.port4Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port4", None, QtGui.QApplication.UnicodeUTF8))
        self.port5Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port5", None, QtGui.QApplication.UnicodeUTF8))
        self.port6Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port6", None, QtGui.QApplication.UnicodeUTF8))
        self.port7Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port7", None, QtGui.QApplication.UnicodeUTF8))
        self.port8Label.setText(QtGui.QApplication.translate("switchBoxWidget", "port8", None, QtGui.QApplication.UnicodeUTF8))
        self.aliasesGroupBox.setTitle(QtGui.QApplication.translate("switchBoxWidget", "Aliases", None, QtGui.QApplication.UnicodeUTF8))
        self.alias8Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias8", None, QtGui.QApplication.UnicodeUTF8))
        self.alias7Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias7", None, QtGui.QApplication.UnicodeUTF8))
        self.alias6Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias6", None, QtGui.QApplication.UnicodeUTF8))
        self.alias1Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias1", None, QtGui.QApplication.UnicodeUTF8))
        self.alias3Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias3", None, QtGui.QApplication.UnicodeUTF8))
        self.alias2Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias2", None, QtGui.QApplication.UnicodeUTF8))
        self.alias4Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias4", None, QtGui.QApplication.UnicodeUTF8))
        self.alias5Label.setText(QtGui.QApplication.translate("switchBoxWidget", "alias5", None, QtGui.QApplication.UnicodeUTF8))
        self.for1Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for2Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for3Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for4Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for5Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for6Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for7Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))
        self.for8Label.setText(QtGui.QApplication.translate("switchBoxWidget", "for", None, QtGui.QApplication.UnicodeUTF8))

