# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\GRA8HI\Documents\Projects\Test_Environment_Client\qt_designer\USBMuxWidget.ui'
#
# Created: Tue Feb 14 16:01:06 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_USBMuxWidget(object):
    def setupUi(self, USBMuxWidget):
        USBMuxWidget.setObjectName("USBMuxWidget")
        self.gridLayout = QtGui.QGridLayout(USBMuxWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.outputGroupBox = QtGui.QGroupBox(USBMuxWidget)
        self.outputGroupBox.setObjectName("outputGroupBox")
        self.formLayout_2 = QtGui.QFormLayout(self.outputGroupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.output1Label = QtGui.QLabel(self.outputGroupBox)
        self.output1Label.setObjectName("output1Label")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.output1Label)
        self.output1LineEdit = QtGui.QLineEdit(self.outputGroupBox)
        self.output1LineEdit.setObjectName("output1LineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.output1LineEdit)
        self.output2Label = QtGui.QLabel(self.outputGroupBox)
        self.output2Label.setObjectName("output2Label")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.output2Label)
        self.output2LineEdit = QtGui.QLineEdit(self.outputGroupBox)
        self.output2LineEdit.setObjectName("output2LineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.output2LineEdit)
        self.output3Label = QtGui.QLabel(self.outputGroupBox)
        self.output3Label.setObjectName("output3Label")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.output3Label)
        self.output3LineEdit = QtGui.QLineEdit(self.outputGroupBox)
        self.output3LineEdit.setObjectName("output3LineEdit")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.output3LineEdit)
        self.output4Label = QtGui.QLabel(self.outputGroupBox)
        self.output4Label.setObjectName("output4Label")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.output4Label)
        self.output4LineEdit = QtGui.QLineEdit(self.outputGroupBox)
        self.output4LineEdit.setObjectName("output4LineEdit")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.output4LineEdit)
        self.gridLayout.addWidget(self.outputGroupBox, 1, 1, 1, 1)
        self.inputGroupBox = QtGui.QGroupBox(USBMuxWidget)
        self.inputGroupBox.setObjectName("inputGroupBox")
        self.formLayout = QtGui.QFormLayout(self.inputGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.input1Label = QtGui.QLabel(self.inputGroupBox)
        self.input1Label.setObjectName("input1Label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.input1Label)
        self.input1LineEdit = QtGui.QLineEdit(self.inputGroupBox)
        self.input1LineEdit.setObjectName("input1LineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.input1LineEdit)
        self.input2Label = QtGui.QLabel(self.inputGroupBox)
        self.input2Label.setObjectName("input2Label")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.input2Label)
        self.input2LineEdit = QtGui.QLineEdit(self.inputGroupBox)
        self.input2LineEdit.setObjectName("input2LineEdit")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.input2LineEdit)
        self.gridLayout.addWidget(self.inputGroupBox, 1, 0, 1, 1)
        self.defaultFrame = QtGui.QFrame(USBMuxWidget)
        self.defaultFrame.setObjectName("defaultFrame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.defaultFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.defaultLabel = QtGui.QLabel(self.defaultFrame)
        self.defaultLabel.setObjectName("defaultLabel")
        self.horizontalLayout_2.addWidget(self.defaultLabel)
        self.defaultInputComboBox = QtGui.QComboBox(self.defaultFrame)
        self.defaultInputComboBox.setObjectName("defaultInputComboBox")
        self.horizontalLayout_2.addWidget(self.defaultInputComboBox)
        self.defaultOuputComboBox = QtGui.QComboBox(self.defaultFrame)
        self.defaultOuputComboBox.setObjectName("defaultOuputComboBox")
        self.horizontalLayout_2.addWidget(self.defaultOuputComboBox)
        self.gridLayout.addWidget(self.defaultFrame, 2, 0, 1, 2)
        self.typeFrame = QtGui.QFrame(USBMuxWidget)
        self.typeFrame.setObjectName("typeFrame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.typeFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typeLabel = QtGui.QLabel(self.typeFrame)
        self.typeLabel.setObjectName("typeLabel")
        self.horizontalLayout.addWidget(self.typeLabel)
        self.typeComboBox = QtGui.QComboBox(self.typeFrame)
        self.typeComboBox.setObjectName("typeComboBox")
        self.horizontalLayout.addWidget(self.typeComboBox)
        self.gridLayout.addWidget(self.typeFrame, 0, 0, 1, 2)

        self.retranslateUi(USBMuxWidget)
        QtCore.QMetaObject.connectSlotsByName(USBMuxWidget)

    def retranslateUi(self, USBMuxWidget):
        USBMuxWidget.setWindowTitle(QtGui.QApplication.translate("USBMuxWidget", "USB Multiplexer", None, QtGui.QApplication.UnicodeUTF8))
        self.outputGroupBox.setTitle(QtGui.QApplication.translate("USBMuxWidget", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.output1Label.setText(QtGui.QApplication.translate("USBMuxWidget", "output1", None, QtGui.QApplication.UnicodeUTF8))
        self.output2Label.setText(QtGui.QApplication.translate("USBMuxWidget", "output2", None, QtGui.QApplication.UnicodeUTF8))
        self.output3Label.setText(QtGui.QApplication.translate("USBMuxWidget", "output3", None, QtGui.QApplication.UnicodeUTF8))
        self.output4Label.setText(QtGui.QApplication.translate("USBMuxWidget", "output4", None, QtGui.QApplication.UnicodeUTF8))
        self.inputGroupBox.setTitle(QtGui.QApplication.translate("USBMuxWidget", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.input1Label.setText(QtGui.QApplication.translate("USBMuxWidget", "input1", None, QtGui.QApplication.UnicodeUTF8))
        self.input2Label.setText(QtGui.QApplication.translate("USBMuxWidget", "input2", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultLabel.setText(QtGui.QApplication.translate("USBMuxWidget", "Default Connection:", None, QtGui.QApplication.UnicodeUTF8))
        self.typeLabel.setText(QtGui.QApplication.translate("USBMuxWidget", "Type:", None, QtGui.QApplication.UnicodeUTF8))

